package taxonomy

import "testing"

const testdata = `
{
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "url": "http://www.desmoinesregister.com/story/news/crime-and-courts/2015/07/14/van-meter-taser-fundraiser-modified/30129893/?hootPostID=%5B%22%5B%27e34bfcfff7cf7090f7c60c8ecd6167a8%27%5D%22%5D",
    "totalTransactions": "1",
    "language": "english",
    "taxonomy": [
        {
            "label": "/law, govt and politics/law enforcement/police",
            "score": "0.589151"
        },
        {
            "confident": "no",
            "label": "/law, govt and politics/law enforcement",
            "score": "0.33143"
        },
        {
            "confident": "no",
            "label": "/education/school",
            "score": "0.238189"
        }
    ]
}`

func TestTaxonomy(t *testing.T) {
	tax := Taxonomy{}
	err := tax.Decode([]byte(testdata))
	if err != nil {
		t.Error(err)
	}
	if len(tax.Results) != 3 {
		t.Errorf("Expected 3 results got %v\n", len(tax.Results))
	}
}
