// Copyright 2015 Davin Hills. All rights reserved.
// MIT license. License details can be found in the LICENSE file.
package relation

import "testing"

const testdata = `
{
                    "status": "OK",
                    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
                    "url": "http://www.desmoinesregister.com/story/news/crime-and-courts/2015/07/14/van-meter-taser-fundraiser-modified/30129893/?hootPostID=%5B%22%5B%27e34bfcfff7cf7090f7c60c8ecd6167a8%27%5D%22%5D",
                    "totalTransactions": "4",
                    "language": "english",
                    "relations": [
                        {
                            "sentence": "Instead of slinging electricity at a Van Meter city official, the winner of a fundraising raffle will instead shoot a police Taser at a\u00A0target.",
                            "subject": {
                                "text": "electricity",
                                "keywords": [
                                    {
                                        "text": "electricity"
                                    }
                                ]
                            },
                            "action": {
                                "text": "slinging",
                                "lemmatized": "sling",
                                "verb": {
                                    "text": "sling",
                                    "tense": "future"
                                }
                            },
                            "location": {
                                "text": "at a Van Meter city official, the winner of a fundraising raffle",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.714205"
                                },
                                "entities": [
                                    {
                                        "type": "Facility",
                                        "text": "Van Meter"
                                    },
                                    {
                                        "type": "JobTitle",
                                        "text": "official"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": "Instead of slinging electricity at a Van Meter city official, the winner of a fundraising raffle will instead shoot a police Taser at a\u00A0target.",
                            "subject": {
                                "text": "a fundraising raffle",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.644293"
                                },
                                "keywords": [
                                    {
                                        "text": "raffle"
                                    }
                                ]
                            },
                            "action": {
                                "text": "will instead shoot",
                                "lemmatized": "will instead shoot",
                                "verb": {
                                    "text": "shoot",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "a police Taser",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.659592"
                                },
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.590874"
                                },
                                "keywords": [
                                    {
                                        "text": "police Taser"
                                    }
                                ]
                            },
                            "location": {
                                "text": "at a\u00A0target",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.347751"
                                }
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "The city",
                                "keywords": [
                                    {
                                        "text": "city"
                                    }
                                ]
                            },
                            "action": {
                                "text": "is",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "modifying a plan that would have allowed citizens",
                                "keywords": [
                                    {
                                        "text": "citizens"
                                    },
                                    {
                                        "text": "plan"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "The city",
                                "keywords": [
                                    {
                                        "text": "city"
                                    }
                                ]
                            },
                            "action": {
                                "text": "is modifying",
                                "lemmatized": "be modify",
                                "verb": {
                                    "text": "modify",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on",
                                "entities": [
                                    {
                                        "type": "Quantity",
                                        "text": "$5"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "raffle tickets"
                                    },
                                    {
                                        "text": "Taser"
                                    },
                                    {
                                        "text": "chance"
                                    },
                                    {
                                        "text": "citizens"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "a plan",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.210541"
                                },
                                "keywords": [
                                    {
                                        "text": "plan"
                                    }
                                ]
                            },
                            "action": {
                                "text": "would have allowed",
                                "lemmatized": "would have allow",
                                "verb": {
                                    "text": "allow",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.26519"
                                },
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.278179"
                                },
                                "entities": [
                                    {
                                        "type": "JobTitle",
                                        "text": "Administrator"
                                    },
                                    {
                                        "type": "Person",
                                        "text": "Jake Anderson"
                                    },
                                    {
                                        "type": "Person",
                                        "text": "Bob Lacy"
                                    },
                                    {
                                        "type": "Quantity",
                                        "text": "$5"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "City Administrator Jake"
                                    },
                                    {
                                        "text": "Councilman Bob Lacy"
                                    },
                                    {
                                        "text": "raffle tickets"
                                    },
                                    {
                                        "text": "Taser"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "citizens",
                                "keywords": [
                                    {
                                        "text": "citizens"
                                    }
                                ]
                            },
                            "action": {
                                "text": "to use",
                                "lemmatized": "to use",
                                "verb": {
                                    "text": "use",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "a Taser",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.519103"
                                },
                                "keywords": [
                                    {
                                        "text": "Taser"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Two businesses are promising money toward fundraising efforts if the city agrees to remove the human element from the Tasing.",
                            "subject": {
                                "text": "Two businesses",
                                "keywords": [
                                    {
                                        "text": "businesses"
                                    }
                                ]
                            },
                            "action": {
                                "text": "are promising",
                                "lemmatized": "be promise",
                                "verb": {
                                    "text": "promise",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "money",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.359481"
                                },
                                "keywords": [
                                    {
                                        "text": "money"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Two businesses are promising money toward fundraising efforts if the city agrees to remove the human element from the Tasing.",
                            "subject": {
                                "text": "the city",
                                "keywords": [
                                    {
                                        "text": "city"
                                    }
                                ]
                            },
                            "action": {
                                "text": "agrees",
                                "lemmatized": "agree",
                                "verb": {
                                    "text": "agree",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "to remove the human element from the Tasing",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.493173"
                                },
                                "entities": [
                                    {
                                        "type": "City",
                                        "text": "Tasing"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "human element"
                                    },
                                    {
                                        "text": "Tasing"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Two businesses are promising money toward fundraising efforts if the city agrees to remove the human element from the Tasing.",
                            "subject": {
                                "text": "the city",
                                "keywords": [
                                    {
                                        "text": "city"
                                    }
                                ]
                            },
                            "action": {
                                "text": "to remove",
                                "lemmatized": "to remove",
                                "verb": {
                                    "text": "remove",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "the human element",
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.594941"
                                },
                                "keywords": [
                                    {
                                        "text": "human element"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Police Chief Bill Daggett said both businesses called Dallas County dispatch asking to speak with the him about modifying the event.",
                            "subject": {
                                "text": "Police Chief Bill Daggett",
                                "entities": [
                                    {
                                        "type": "FieldTerminology",
                                        "text": "Police Chief"
                                    },
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Daggett"
                                    },
                                    {
                                        "text": "Police"
                                    }
                                ]
                            },
                            "action": {
                                "text": "said",
                                "lemmatized": "say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "both businesses called Dallas County dispatch asking to speak with the him about modifying the event",
                                "entities": [
                                    {
                                        "type": "StateOrCounty",
                                        "text": "Dallas County",
                                        "disambiguated": {
                                            "subType": [
                                                "Location",
                                                "AdministrativeDivision",
                                                "USCounty"
                                            ],
                                            "name": "Dallas County, Iowa",
                                            "geo": "41.68277777777778 -94.035",
                                            "website": "http://www.co.dallas.ia.us",
                                            "dbpedia": "http://dbpedia.org/resource/Dallas_County,_Iowa",
                                            "freebase": "http://rdf.freebase.com/ns/m.0nsbv",
                                            "census": "http://www.rdfabout.com/rdf/usgov/geo/us/ia/counties/dallas_county",
                                            "yago": "http://yago-knowledge.org/resource/Dallas_County,_Iowa",
                                            "geonames": "http://sws.geonames.org/4853335/"
                                        }
                                    },
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Dallas County dispatch"
                                    },
                                    {
                                        "text": "businesses"
                                    },
                                    {
                                        "text": "event"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Police Chief Bill Daggett said both businesses called Dallas County dispatch asking to speak with the him about modifying the event.",
                            "subject": {
                                "text": "both businesses",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.274541"
                                },
                                "keywords": [
                                    {
                                        "text": "businesses"
                                    }
                                ]
                            },
                            "action": {
                                "text": "called",
                                "lemmatized": "call",
                                "verb": {
                                    "text": "call",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "County dispatch",
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.237388"
                                },
                                "keywords": [
                                    {
                                        "text": "County dispatch"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "They"
                            },
                            "action": {
                                "text": "wanted",
                                "lemmatized": "want",
                                "verb": {
                                    "text": "want",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "an opportunity to get their company out in the public eye and do something good too",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.832087"
                                },
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.545001"
                                },
                                "keywords": [
                                    {
                                        "text": "public eye"
                                    },
                                    {
                                        "text": "opportunity"
                                    },
                                    {
                                        "text": "company"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "They"
                            },
                            "action": {
                                "text": "to get",
                                "lemmatized": "to get",
                                "verb": {
                                    "text": "get",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "their company",
                                "keywords": [
                                    {
                                        "text": "company"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "They"
                            },
                            "action": {
                                "text": "do",
                                "lemmatized": "do",
                                "verb": {
                                    "text": "do",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "something good",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.61185"
                                }
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "Daggett",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Daggett"
                                    }
                                ]
                            },
                            "action": {
                                "text": "told",
                                "lemmatized": "tell",
                                "verb": {
                                    "text": "tell",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "We never expected to have national or international attention or expected to have companies say we'll help you out",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.475187"
                                },
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.210328"
                                },
                                "keywords": [
                                    {
                                        "text": "international attention"
                                    },
                                    {
                                        "text": "companies"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "We"
                            },
                            "action": {
                                "text": "expected to have",
                                "lemmatized": "expect to have",
                                "verb": {
                                    "text": "expect",
                                    "tense": "past"
                                }
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "We"
                            },
                            "action": {
                                "text": "expected to have",
                                "lemmatized": "expect to have",
                                "verb": {
                                    "text": "have",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "national or international attention",
                                "keywords": [
                                    {
                                        "text": "international attention"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "We"
                            },
                            "action": {
                                "text": "expected to have",
                                "lemmatized": "expect to have",
                                "verb": {
                                    "text": "have",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "companies",
                                "keywords": [
                                    {
                                        "text": "companies"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "we"
                            },
                            "action": {
                                "text": "help",
                                "lemmatized": "help",
                                "verb": {
                                    "text": "help",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "you",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.431174"
                                }
                            }
                        },
                        {
                            "sentence": " About $4,000 have been raised so far, Daggett said.",
                            "subject": {
                                "text": "About $4,000",
                                "entities": [
                                    {
                                        "type": "Quantity",
                                        "text": "$4,000"
                                    }
                                ]
                            },
                            "action": {
                                "text": "have been raised",
                                "lemmatized": "have be raise",
                                "verb": {
                                    "text": "raise",
                                    "tense": "past"
                                }
                            }
                        },
                        {
                            "sentence": " About $4,000 have been raised so far, Daggett said.",
                            "subject": {
                                "text": "Daggett",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Daggett"
                                    }
                                ]
                            },
                            "action": {
                                "text": "said",
                                "lemmatized": "say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "About $4,000 have been raised so far",
                                "entities": [
                                    {
                                        "type": "Quantity",
                                        "text": "$4,000"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " The ACLU of Iowa and a physician from the University of Iowa expressed concerns over the original Tasing event.",
                            "subject": {
                                "text": "The ACLU of Iowa and a physician from the University of Iowa",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.606046"
                                },
                                "entities": [
                                    {
                                        "type": "StateOrCounty",
                                        "text": "Iowa",
                                        "disambiguated": {
                                            "subType": [
                                                "Location",
                                                "PoliticalDistrict",
                                                "AdministrativeDivision",
                                                "GovernmentalJurisdiction",
                                                "USState"
                                            ],
                                            "name": "Iowa",
                                            "website": "http://www.iowa.gov",
                                            "dbpedia": "http://dbpedia.org/resource/Iowa",
                                            "freebase": "http://rdf.freebase.com/ns/m.03s0w",
                                            "opencyc": "http://sw.opencyc.org/concept/Mx4rvVi3ipwpEbGdrcN5Y29ycA",
                                            "census": "http://www.rdfabout.com/rdf/usgov/geo/us/ia",
                                            "yago": "http://yago-knowledge.org/resource/Iowa"
                                        }
                                    },
                                    {
                                        "type": "Organization",
                                        "text": "University of Iowa",
                                        "disambiguated": {
                                            "subType": [
                                                "CollegeUniversity",
                                                "University"
                                            ],
                                            "name": "University of Iowa",
                                            "geo": "41.655833333333334 -91.525",
                                            "website": "http://www.uiowa.edu/",
                                            "dbpedia": "http://dbpedia.org/resource/University_of_Iowa",
                                            "freebase": "http://rdf.freebase.com/ns/m.01j_9c",
                                            "opencyc": "http://sw.opencyc.org/concept/Mx4rwBa-f5wpEbGdrcN5Y29ycA",
                                            "yago": "http://yago-knowledge.org/resource/University_of_Iowa",
                                            "geonames": "http://sws.geonames.org/4879820/"
                                        }
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "ACLU"
                                    },
                                    {
                                        "text": "Iowa"
                                    },
                                    {
                                        "text": "physician"
                                    },
                                    {
                                        "text": "University"
                                    }
                                ]
                            },
                            "action": {
                                "text": "expressed",
                                "lemmatized": "express",
                                "verb": {
                                    "text": "express",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "concerns",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.678918"
                                },
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.430361"
                                },
                                "keywords": [
                                    {
                                        "text": "concerns"
                                    }
                                ]
                            },
                            "location": {
                                "text": "over the original Tasing event"
                            }
                        },
                        {
                            "sentence": " \"I am pleased to hear that Van Meter has listened to the very important concerns raised about the Taser raffle.",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "am",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "pleased to hear that Van Meter has listened to the very important concerns raised about the Taser raffle",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.773457"
                                },
                                "entities": [
                                    {
                                        "type": "Company",
                                        "text": "Van Meter"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Taser raffle"
                                    },
                                    {
                                        "text": "Van Meter"
                                    },
                                    {
                                        "text": "important concerns"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"I am pleased to hear that Van Meter has listened to the very important concerns raised about the Taser raffle.",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "am pleased to hear",
                                "lemmatized": "be please to hear",
                                "verb": {
                                    "text": "hear",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "that Van Meter has listened",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.272687"
                                },
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.779636"
                                },
                                "entities": [
                                    {
                                        "type": "Company",
                                        "text": "Van Meter"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Van Meter"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "hope",
                                "lemmatized": "hope",
                                "verb": {
                                    "text": "hope",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.768115"
                                },
                                "entities": [
                                    {
                                        "type": "FieldTerminology",
                                        "text": "law enforcement"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "properly trained law"
                                    },
                                    {
                                        "text": "dangerous Tasers"
                                    },
                                    {
                                        "text": "clear policies"
                                    },
                                    {
                                        "text": "better understanding"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "by properly trained law enforcement personnel operating under clear policies",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.644305"
                                },
                                "entities": [
                                    {
                                        "type": "FieldTerminology",
                                        "text": "law enforcement"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "properly trained law"
                                    },
                                    {
                                        "text": "clear policies"
                                    },
                                    {
                                        "text": "enforcement personnel"
                                    }
                                ]
                            },
                            "action": {
                                "text": "are only used",
                                "lemmatized": "be only use",
                                "verb": {
                                    "text": "use",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "they",
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.501035"
                                }
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "they"
                            },
                            "action": {
                                "text": "trained",
                                "lemmatized": "train",
                                "verb": {
                                    "text": "train",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "law enforcement personnel",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.236593"
                                },
                                "entities": [
                                    {
                                        "type": "FieldTerminology",
                                        "text": "law enforcement"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "law enforcement personnel"
                                    }
                                ]
                            },
                            "location": {
                                "text": "operating under clear policies",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.250402"
                                }
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "Jeremy Rosen, director of ACLU of Iowa,",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.659058"
                                },
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Jeremy Rosen",
                                        "disambiguated": {
                                            "name": "Jeremy Rosen",
                                            "dbpedia": "http://dbpedia.org/resource/Jeremy_Rosen",
                                            "freebase": "http://rdf.freebase.com/ns/m.02wz27p"
                                        }
                                    },
                                    {
                                        "type": "JobTitle",
                                        "text": "director"
                                    },
                                    {
                                        "type": "StateOrCounty",
                                        "text": "Iowa",
                                        "disambiguated": {
                                            "subType": [
                                                "Location",
                                                "PoliticalDistrict",
                                                "AdministrativeDivision",
                                                "GovernmentalJurisdiction",
                                                "USState"
                                            ],
                                            "name": "Iowa",
                                            "website": "http://www.iowa.gov",
                                            "dbpedia": "http://dbpedia.org/resource/Iowa",
                                            "freebase": "http://rdf.freebase.com/ns/m.03s0w",
                                            "opencyc": "http://sw.opencyc.org/concept/Mx4rvVi3ipwpEbGdrcN5Y29ycA",
                                            "census": "http://www.rdfabout.com/rdf/usgov/geo/us/ia",
                                            "yago": "http://yago-knowledge.org/resource/Iowa"
                                        }
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Jeremy Rosen"
                                    },
                                    {
                                        "text": "ACLU"
                                    },
                                    {
                                        "text": "director"
                                    },
                                    {
                                        "text": "Iowa"
                                    }
                                ]
                            },
                            "action": {
                                "text": "said",
                                "lemmatized": "say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.73062"
                                },
                                "entities": [
                                    {
                                        "type": "FieldTerminology",
                                        "text": "law enforcement"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "properly trained law"
                                    },
                                    {
                                        "text": "dangerous Tasers"
                                    },
                                    {
                                        "text": "clear policies"
                                    },
                                    {
                                        "text": "better understanding"
                                    }
                                ]
                            },
                            "location": {
                                "text": "in a statement"
                            }
                        },
                        {
                            "sentence": " Those who purchased a ticket with the intention of Tasing government officials can call Van Meter City Hall and get their money back, the news release states.",
                            "subject": {
                                "text": "Those"
                            },
                            "action": {
                                "text": "purchased",
                                "lemmatized": "purchase",
                                "verb": {
                                    "text": "purchase",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "a ticket",
                                "keywords": [
                                    {
                                        "text": "ticket"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Those who purchased a ticket with the intention of Tasing government officials can call Van Meter City Hall and get their money back, the news release states.",
                            "subject": {
                                "text": "Tasing government officials",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.384523"
                                },
                                "entities": [
                                    {
                                        "type": "City",
                                        "text": "Tasing"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "government officials"
                                    }
                                ]
                            },
                            "action": {
                                "text": "can call",
                                "lemmatized": "can call",
                                "verb": {
                                    "text": "call",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "Van Meter City Hall",
                                "entities": [
                                    {
                                        "type": "Facility",
                                        "text": "Van Meter City Hall"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Van Meter City"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Those who purchased a ticket with the intention of Tasing government officials can call Van Meter City Hall and get their money back, the news release states.",
                            "subject": {
                                "text": "Those"
                            },
                            "action": {
                                "text": "get",
                                "lemmatized": "get",
                                "verb": {
                                    "text": "get",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "their money",
                                "keywords": [
                                    {
                                        "text": "money"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family, wrote Daggett an undated letter promising to help fill the funding gap after community efforts.",
                            "subject": {
                                "text": "J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family,",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "J.C. Owens"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "J.C. Owens"
                                    },
                                    {
                                        "text": "authors"
                                    },
                                    {
                                        "text": "book"
                                    },
                                    {
                                        "text": "guide"
                                    }
                                ]
                            },
                            "action": {
                                "text": "wrote",
                                "lemmatized": "write",
                                "verb": {
                                    "text": "write",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "an undated letter promising to help fill the funding gap after community efforts",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.209255"
                                },
                                "keywords": [
                                    {
                                        "text": "undated letter"
                                    },
                                    {
                                        "text": "funding gap"
                                    },
                                    {
                                        "text": "community efforts"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family, wrote Daggett an undated letter promising to help fill the funding gap after community efforts.",
                            "subject": {
                                "text": "an undated letter",
                                "keywords": [
                                    {
                                        "text": "undated letter"
                                    }
                                ]
                            },
                            "action": {
                                "text": "help",
                                "lemmatized": "help",
                                "verb": {
                                    "text": "help",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "fill the funding gap",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.431174"
                                },
                                "keywords": [
                                    {
                                        "text": "funding gap"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family, wrote Daggett an undated letter promising to help fill the funding gap after community efforts.",
                            "subject": {
                                "text": "the funding gap",
                                "keywords": [
                                    {
                                        "text": "gap"
                                    }
                                ]
                            },
                            "action": {
                                "text": "promising to help fill",
                                "lemmatized": "promise to help fill",
                                "verb": {
                                    "text": "fill",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "an undated letter",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.742013"
                                },
                                "keywords": [
                                    {
                                        "text": "undated letter"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"My only concern is in the use of a taser on a community citizen or official in your fundraising efforts,\" Owens wrote.",
                            "subject": {
                                "text": "My only concern",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.717492"
                                },
                                "keywords": [
                                    {
                                        "text": "concern"
                                    }
                                ]
                            },
                            "action": {
                                "text": "is",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "in the use of a taser on a community citizen or official in your fundraising efforts",
                                "entities": [
                                    {
                                        "type": "JobTitle",
                                        "text": "official"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "fundraising efforts"
                                    },
                                    {
                                        "text": "community citizen"
                                    },
                                    {
                                        "text": "taser"
                                    },
                                    {
                                        "text": "official"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"My only concern is in the use of a taser on a community citizen or official in your fundraising efforts,\" Owens wrote.",
                            "subject": {
                                "text": "Owens",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "J.C. Owens"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Owens"
                                    }
                                ]
                            },
                            "action": {
                                "text": "wrote",
                                "lemmatized": "write",
                                "verb": {
                                    "text": "write",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "My only concern is in the use of a taser on a community citizen or official in your fundraising efforts",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.617784"
                                },
                                "entities": [
                                    {
                                        "type": "JobTitle",
                                        "text": "official"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "fundraising efforts"
                                    },
                                    {
                                        "text": "community citizen"
                                    },
                                    {
                                        "text": "taser"
                                    },
                                    {
                                        "text": "concern"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"If the fundraising effort could be more directed in an educational direction on the use of tasers and non lethal force, I would be very much willing to extend our organizations support for your commendable fundraising efforts.\"",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "to extend",
                                "lemmatized": "to extend",
                                "verb": {
                                    "text": "extend",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "our organizations support",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.602452"
                                },
                                "keywords": [
                                    {
                                        "text": "organizations"
                                    },
                                    {
                                        "text": "support"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " \"If the fundraising effort could be more directed in an educational direction on the use of tasers and non lethal force, I would be very much willing to extend our organizations support for your commendable fundraising efforts.\"",
                            "subject": {
                                "text": "our organizations",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.262874"
                                },
                                "keywords": [
                                    {
                                        "text": "organizations"
                                    }
                                ]
                            },
                            "action": {
                                "text": "support",
                                "lemmatized": "support",
                                "verb": {
                                    "text": "support",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "for your commendable fundraising efforts",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.45603"
                                },
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.500387"
                                },
                                "keywords": [
                                    {
                                        "text": "commendable fundraising efforts"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "Daggett",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Daggett"
                                    }
                                ]
                            },
                            "action": {
                                "text": "has",
                                "lemmatized": "have",
                                "verb": {
                                    "text": "have",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "said he wished to raise at least $10,000 toward purchasing a second squad car",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.554799"
                                },
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    },
                                    {
                                        "type": "FieldTerminology",
                                        "text": "squad car"
                                    },
                                    {
                                        "type": "Quantity",
                                        "text": "$10,000"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "squad car"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "Daggett",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Daggett"
                                    }
                                ]
                            },
                            "action": {
                                "text": "has said",
                                "lemmatized": "have say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "he wished to raise at least $10,000 toward purchasing a second squad car",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.529393"
                                },
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    },
                                    {
                                        "type": "FieldTerminology",
                                        "text": "squad car"
                                    },
                                    {
                                        "type": "Quantity",
                                        "text": "$10,000"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "squad car"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "he",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ]
                            },
                            "action": {
                                "text": "purchasing",
                                "lemmatized": "purchase",
                                "verb": {
                                    "text": "purchase",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "a second squad car",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.38895"
                                },
                                "entities": [
                                    {
                                        "type": "FieldTerminology",
                                        "text": "squad car"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "squad car"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "he",
                                "entities": [
                                    {
                                        "type": "Person",
                                        "text": "Bill Daggett"
                                    }
                                ]
                            },
                            "action": {
                                "text": "adding",
                                "lemmatized": "add",
                                "verb": {
                                    "text": "add",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "to the six-person force and purchase oxygen masks and defibrillators that officers carry daily",
                                "sentimentFromSubject": {
                                    "type": "positive",
                                    "score": "0.245876"
                                },
                                "keywords": [
                                    {
                                        "text": "purchase oxygen masks"
                                    },
                                    {
                                        "text": "six-person force"
                                    },
                                    {
                                        "text": "defibrillators"
                                    },
                                    {
                                        "text": "officers"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "officers",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.207276"
                                },
                                "keywords": [
                                    {
                                        "text": "officers"
                                    }
                                ]
                            },
                            "action": {
                                "text": "carry",
                                "lemmatized": "carry",
                                "verb": {
                                    "text": "carry",
                                    "tense": "present"
                                }
                            }
                        },
                        {
                            "sentence": " A second Des Moines-based start-up called Wise Tactical Products and Uniforms will donate about $2,000 for all emergency lighting and siren equipment for the second patrol vehicle, again asking that no one be Tasered in exchange, according to the news release.",
                            "subject": {
                                "text": "A second Des Moines-based start-up",
                                "keywords": [
                                    {
                                        "text": "Des Moines-based start-up"
                                    }
                                ]
                            },
                            "action": {
                                "text": "called",
                                "lemmatized": "call",
                                "verb": {
                                    "text": "call",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "Wise Tactical Products and Uniforms",
                                "sentimentFromSubject": {
                                    "type": "negative",
                                    "score": "-0.237388"
                                },
                                "entities": [
                                    {
                                        "type": "Company",
                                        "text": "Wise Tactical Products"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "Wise Tactical Products"
                                    },
                                    {
                                        "text": "Uniforms"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " A second Des Moines-based start-up called Wise Tactical Products and Uniforms will donate about $2,000 for all emergency lighting and siren equipment for the second patrol vehicle, again asking that no one be Tasered in exchange, according to the news release.",
                            "subject": {
                                "text": "A second Des Moines-based start-up",
                                "keywords": [
                                    {
                                        "text": "Des Moines-based start-up"
                                    }
                                ]
                            },
                            "action": {
                                "text": "asking",
                                "lemmatized": "ask",
                                "verb": {
                                    "text": "ask",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "that no one be Tasered in exchange",
                                "sentiment": {
                                    "type": "negative",
                                    "score": "-0.815809"
                                },
                                "keywords": [
                                    {
                                        "text": "Tasered"
                                    },
                                    {
                                        "text": "exchange"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " The city is still selling its $5 raffle tickets, according to a flier on the city's Facebook page.",
                            "subject": {
                                "text": "The city",
                                "keywords": [
                                    {
                                        "text": "city"
                                    }
                                ]
                            },
                            "action": {
                                "text": "is",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "still selling its $5 raffle tickets",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.300646"
                                },
                                "entities": [
                                    {
                                        "type": "Quantity",
                                        "text": "$5"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "raffle tickets"
                                    }
                                ]
                            }
                        },
                        {
                            "sentence": " The city is still selling its $5 raffle tickets, according to a flier on the city's Facebook page.",
                            "subject": {
                                "text": "The city",
                                "keywords": [
                                    {
                                        "text": "city"
                                    }
                                ]
                            },
                            "action": {
                                "text": "selling",
                                "lemmatized": "sell",
                                "verb": {
                                    "text": "sell",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "its $5 raffle tickets",
                                "sentiment": {
                                    "type": "positive",
                                    "score": "0.433104"
                                },
                                "entities": [
                                    {
                                        "type": "Quantity",
                                        "text": "$5"
                                    }
                                ],
                                "keywords": [
                                    {
                                        "text": "raffle tickets"
                                    }
                                ]
                            }
                        }
                    ]
                }
								`

func TestRelation(t *testing.T) {
	rel := Relations{}
	err := rel.Decode([]byte(testdata))
	if err != nil {
		t.Error(err)
	}
	if len(rel.Results) != 47 {
		t.Errorf("Expected 47 results got %v\n", len(rel.Results))
	}
}
