// Copyright 2015 Davin Hills. All rights reserved.
// MIT license. License details can be found in the LICENSE file.
package relation

import "testing"

const testdata = `
{
                    "status": "OK",
                    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
                    "url": "http://www.desmoinesregister.com/story/news/crime-and-courts/2015/07/14/van-meter-taser-fundraiser-modified/30129893/?hootPostID=%5B%22%5B%27e34bfcfff7cf7090f7c60c8ecd6167a8%27%5D%22%5D",
                    "language": "english",
                    "relations": [
                        {
                            "sentence": "Instead of slinging electricity at a Van Meter city official, the winner of a fundraising raffle will instead shoot a police Taser at a\u00A0target.",
                            "subject": {
                                "text": "electricity"
                            },
                            "action": {
                                "text": "slinging",
                                "lemmatized": "sling",
                                "verb": {
                                    "text": "sling",
                                    "tense": "future"
                                }
                            },
                            "location": {
                                "text": "at a Van Meter city official, the winner of a fundraising raffle"
                            }
                        },
                        {
                            "sentence": "Instead of slinging electricity at a Van Meter city official, the winner of a fundraising raffle will instead shoot a police Taser at a\u00A0target.",
                            "subject": {
                                "text": "a fundraising raffle"
                            },
                            "action": {
                                "text": "will instead shoot",
                                "lemmatized": "will instead shoot",
                                "verb": {
                                    "text": "shoot",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "a police Taser"
                            },
                            "location": {
                                "text": "at a\u00A0target"
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "The city"
                            },
                            "action": {
                                "text": "is",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "modifying a plan that would have allowed citizens"
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "The city"
                            },
                            "action": {
                                "text": "is modifying",
                                "lemmatized": "be modify",
                                "verb": {
                                    "text": "modify",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on"
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "a plan"
                            },
                            "action": {
                                "text": "would have allowed",
                                "lemmatized": "would have allow",
                                "verb": {
                                    "text": "allow",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18"
                            }
                        },
                        {
                            "sentence": " The city is modifying a plan that would have allowed citizens to purchase $5 raffle tickets for a chance to use a Taser on either City Administrator Jake Anderson or Councilman Bob Lacy at a celebration on July 18.",
                            "subject": {
                                "text": "citizens"
                            },
                            "action": {
                                "text": "to use",
                                "lemmatized": "to use",
                                "verb": {
                                    "text": "use",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "a Taser"
                            }
                        },
                        {
                            "sentence": " Two businesses are promising money toward fundraising efforts if the city agrees to remove the human element from the Tasing.",
                            "subject": {
                                "text": "Two businesses"
                            },
                            "action": {
                                "text": "are promising",
                                "lemmatized": "be promise",
                                "verb": {
                                    "text": "promise",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "money"
                            }
                        },
                        {
                            "sentence": " Two businesses are promising money toward fundraising efforts if the city agrees to remove the human element from the Tasing.",
                            "subject": {
                                "text": "the city"
                            },
                            "action": {
                                "text": "agrees",
                                "lemmatized": "agree",
                                "verb": {
                                    "text": "agree",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "to remove the human element from the Tasing"
                            }
                        },
                        {
                            "sentence": " Two businesses are promising money toward fundraising efforts if the city agrees to remove the human element from the Tasing.",
                            "subject": {
                                "text": "the city"
                            },
                            "action": {
                                "text": "to remove",
                                "lemmatized": "to remove",
                                "verb": {
                                    "text": "remove",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "the human element"
                            }
                        },
                        {
                            "sentence": " Police Chief Bill Daggett said both businesses called Dallas County dispatch asking to speak with the him about modifying the event.",
                            "subject": {
                                "text": "Police Chief Bill Daggett"
                            },
                            "action": {
                                "text": "said",
                                "lemmatized": "say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "both businesses called Dallas County dispatch asking to speak with the him about modifying the event"
                            }
                        },
                        {
                            "sentence": " Police Chief Bill Daggett said both businesses called Dallas County dispatch asking to speak with the him about modifying the event.",
                            "subject": {
                                "text": "both businesses"
                            },
                            "action": {
                                "text": "called",
                                "lemmatized": "call",
                                "verb": {
                                    "text": "call",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "County dispatch"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "They"
                            },
                            "action": {
                                "text": "wanted",
                                "lemmatized": "want",
                                "verb": {
                                    "text": "want",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "an opportunity to get their company out in the public eye and do something good too"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "They"
                            },
                            "action": {
                                "text": "to get",
                                "lemmatized": "to get",
                                "verb": {
                                    "text": "get",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "their company"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "They"
                            },
                            "action": {
                                "text": "do",
                                "lemmatized": "do",
                                "verb": {
                                    "text": "do",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "something good"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "Daggett"
                            },
                            "action": {
                                "text": "told",
                                "lemmatized": "tell",
                                "verb": {
                                    "text": "tell",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "We never expected to have national or international attention or expected to have companies say we'll help you out"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "We"
                            },
                            "action": {
                                "text": "expected to have",
                                "lemmatized": "expect to have",
                                "verb": {
                                    "text": "expect",
                                    "tense": "past"
                                }
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "We"
                            },
                            "action": {
                                "text": "expected to have",
                                "lemmatized": "expect to have",
                                "verb": {
                                    "text": "have",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "national or international attention"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "We"
                            },
                            "action": {
                                "text": "expected to have",
                                "lemmatized": "expect to have",
                                "verb": {
                                    "text": "have",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "companies"
                            }
                        },
                        {
                            "sentence": " \"They wanted an opportunity to get their company out in the public eye and do something good too,\" Daggett told The Register.\"We never expected to have national or international attention or expected to have companies say we'll help you out.\"",
                            "subject": {
                                "text": "we"
                            },
                            "action": {
                                "text": "help",
                                "lemmatized": "help",
                                "verb": {
                                    "text": "help",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "you"
                            }
                        },
                        {
                            "sentence": " About $4,000 have been raised so far, Daggett said.",
                            "subject": {
                                "text": "About $4,000"
                            },
                            "action": {
                                "text": "have been raised",
                                "lemmatized": "have be raise",
                                "verb": {
                                    "text": "raise",
                                    "tense": "past"
                                }
                            }
                        },
                        {
                            "sentence": " About $4,000 have been raised so far, Daggett said.",
                            "subject": {
                                "text": "Daggett"
                            },
                            "action": {
                                "text": "said",
                                "lemmatized": "say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "About $4,000 have been raised so far"
                            }
                        },
                        {
                            "sentence": " The ACLU of Iowa and a physician from the University of Iowa expressed concerns over the original Tasing event.",
                            "subject": {
                                "text": "The ACLU of Iowa and a physician from the University of Iowa"
                            },
                            "action": {
                                "text": "expressed",
                                "lemmatized": "express",
                                "verb": {
                                    "text": "express",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "concerns"
                            },
                            "location": {
                                "text": "over the original Tasing event"
                            }
                        },
                        {
                            "sentence": " \"I am pleased to hear that Van Meter has listened to the very important concerns raised about the Taser raffle.",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "am",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "pleased to hear that Van Meter has listened to the very important concerns raised about the Taser raffle"
                            }
                        },
                        {
                            "sentence": " \"I am pleased to hear that Van Meter has listened to the very important concerns raised about the Taser raffle.",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "am pleased to hear",
                                "lemmatized": "be please to hear",
                                "verb": {
                                    "text": "hear",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "that Van Meter has listened"
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "hope",
                                "lemmatized": "hope",
                                "verb": {
                                    "text": "hope",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies"
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "by properly trained law enforcement personnel operating under clear policies"
                            },
                            "action": {
                                "text": "are only used",
                                "lemmatized": "be only use",
                                "verb": {
                                    "text": "use",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "they"
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "they"
                            },
                            "action": {
                                "text": "trained",
                                "lemmatized": "train",
                                "verb": {
                                    "text": "train",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "law enforcement personnel"
                            },
                            "location": {
                                "text": "operating under clear policies"
                            }
                        },
                        {
                            "sentence": " I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies,\" Jeremy Rosen, director of ACLU of Iowa, said in a statement.",
                            "subject": {
                                "text": "Jeremy Rosen, director of ACLU of Iowa,"
                            },
                            "action": {
                                "text": "said",
                                "lemmatized": "say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "I hope that this has resulted in a better understanding of how dangerous Tasers can be, and the need to ensure that they are only used by properly trained law enforcement personnel operating under clear policies"
                            },
                            "location": {
                                "text": "in a statement"
                            }
                        },
                        {
                            "sentence": " Those who purchased a ticket with the intention of Tasing government officials can call Van Meter City Hall and get their money back, the news release states.",
                            "subject": {
                                "text": "Those"
                            },
                            "action": {
                                "text": "purchased",
                                "lemmatized": "purchase",
                                "verb": {
                                    "text": "purchase",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "a ticket"
                            }
                        },
                        {
                            "sentence": " Those who purchased a ticket with the intention of Tasing government officials can call Van Meter City Hall and get their money back, the news release states.",
                            "subject": {
                                "text": "Tasing government officials"
                            },
                            "action": {
                                "text": "can call",
                                "lemmatized": "can call",
                                "verb": {
                                    "text": "call",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "Van Meter City Hall"
                            }
                        },
                        {
                            "sentence": " Those who purchased a ticket with the intention of Tasing government officials can call Van Meter City Hall and get their money back, the news release states.",
                            "subject": {
                                "text": "Those"
                            },
                            "action": {
                                "text": "get",
                                "lemmatized": "get",
                                "verb": {
                                    "text": "get",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "their money"
                            }
                        },
                        {
                            "sentence": " J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family, wrote Daggett an undated letter promising to help fill the funding gap after community efforts.",
                            "subject": {
                                "text": "J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family,"
                            },
                            "action": {
                                "text": "wrote",
                                "lemmatized": "write",
                                "verb": {
                                    "text": "write",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "an undated letter promising to help fill the funding gap after community efforts"
                            }
                        },
                        {
                            "sentence": " J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family, wrote Daggett an undated letter promising to help fill the funding gap after community efforts.",
                            "subject": {
                                "text": "an undated letter"
                            },
                            "action": {
                                "text": "help",
                                "lemmatized": "help",
                                "verb": {
                                    "text": "help",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "fill the funding gap"
                            }
                        },
                        {
                            "sentence": " J.C. Owens, one of the authors of the book Aware Not Afraid, a guide to security for the family, wrote Daggett an undated letter promising to help fill the funding gap after community efforts.",
                            "subject": {
                                "text": "the funding gap"
                            },
                            "action": {
                                "text": "promising to help fill",
                                "lemmatized": "promise to help fill",
                                "verb": {
                                    "text": "fill",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "an undated letter"
                            }
                        },
                        {
                            "sentence": " \"My only concern is in the use of a taser on a community citizen or official in your fundraising efforts,\" Owens wrote.",
                            "subject": {
                                "text": "My only concern"
                            },
                            "action": {
                                "text": "is",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "in the use of a taser on a community citizen or official in your fundraising efforts"
                            }
                        },
                        {
                            "sentence": " \"My only concern is in the use of a taser on a community citizen or official in your fundraising efforts,\" Owens wrote.",
                            "subject": {
                                "text": "Owens"
                            },
                            "action": {
                                "text": "wrote",
                                "lemmatized": "write",
                                "verb": {
                                    "text": "write",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "My only concern is in the use of a taser on a community citizen or official in your fundraising efforts"
                            }
                        },
                        {
                            "sentence": " \"If the fundraising effort could be more directed in an educational direction on the use of tasers and non lethal force, I would be very much willing to extend our organizations support for your commendable fundraising efforts.\"",
                            "subject": {
                                "text": "I"
                            },
                            "action": {
                                "text": "to extend",
                                "lemmatized": "to extend",
                                "verb": {
                                    "text": "extend",
                                    "tense": "future"
                                }
                            },
                            "object": {
                                "text": "our organizations support"
                            }
                        },
                        {
                            "sentence": " \"If the fundraising effort could be more directed in an educational direction on the use of tasers and non lethal force, I would be very much willing to extend our organizations support for your commendable fundraising efforts.\"",
                            "subject": {
                                "text": "our organizations"
                            },
                            "action": {
                                "text": "support",
                                "lemmatized": "support",
                                "verb": {
                                    "text": "support",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "for your commendable fundraising efforts"
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "Daggett"
                            },
                            "action": {
                                "text": "has",
                                "lemmatized": "have",
                                "verb": {
                                    "text": "have",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "said he wished to raise at least $10,000 toward purchasing a second squad car"
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "Daggett"
                            },
                            "action": {
                                "text": "has said",
                                "lemmatized": "have say",
                                "verb": {
                                    "text": "say",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "he wished to raise at least $10,000 toward purchasing a second squad car"
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "he"
                            },
                            "action": {
                                "text": "purchasing",
                                "lemmatized": "purchase",
                                "verb": {
                                    "text": "purchase",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "a second squad car"
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "he"
                            },
                            "action": {
                                "text": "adding",
                                "lemmatized": "add",
                                "verb": {
                                    "text": "add",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "to the six-person force and purchase oxygen masks and defibrillators that officers carry daily"
                            }
                        },
                        {
                            "sentence": " Daggett has said he wished to raise at least $10,000 toward purchasing a second squad car, adding more officers to the six-person force and purchase oxygen masks and defibrillators that officers carry daily.",
                            "subject": {
                                "text": "officers"
                            },
                            "action": {
                                "text": "carry",
                                "lemmatized": "carry",
                                "verb": {
                                    "text": "carry",
                                    "tense": "present"
                                }
                            }
                        },
                        {
                            "sentence": " A second Des Moines-based start-up called Wise Tactical Products and Uniforms will donate about $2,000 for all emergency lighting and siren equipment for the second patrol vehicle, again asking that no one be Tasered in exchange, according to the news release.",
                            "subject": {
                                "text": "A second Des Moines-based start-up"
                            },
                            "action": {
                                "text": "called",
                                "lemmatized": "call",
                                "verb": {
                                    "text": "call",
                                    "tense": "past"
                                }
                            },
                            "object": {
                                "text": "Wise Tactical Products and Uniforms"
                            }
                        },
                        {
                            "sentence": " A second Des Moines-based start-up called Wise Tactical Products and Uniforms will donate about $2,000 for all emergency lighting and siren equipment for the second patrol vehicle, again asking that no one be Tasered in exchange, according to the news release.",
                            "subject": {
                                "text": "A second Des Moines-based start-up"
                            },
                            "action": {
                                "text": "asking",
                                "lemmatized": "ask",
                                "verb": {
                                    "text": "ask",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "that no one be Tasered in exchange"
                            }
                        },
                        {
                            "sentence": " The city is still selling its $5 raffle tickets, according to a flier on the city's Facebook page.",
                            "subject": {
                                "text": "The city"
                            },
                            "action": {
                                "text": "is",
                                "lemmatized": "be",
                                "verb": {
                                    "text": "be",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "still selling its $5 raffle tickets"
                            }
                        },
                        {
                            "sentence": " The city is still selling its $5 raffle tickets, according to a flier on the city's Facebook page.",
                            "subject": {
                                "text": "The city"
                            },
                            "action": {
                                "text": "selling",
                                "lemmatized": "sell",
                                "verb": {
                                    "text": "sell",
                                    "tense": "present"
                                }
                            },
                            "object": {
                                "text": "its $5 raffle tickets"
                            }
                        }
                    ]
                }

`

func TestRelation(t *testing.T) {
	rel := Relation{}
	err := rel.Decode([]byte(testdata))
	if err != nil {
		t.Error(err)
	}
	if len(rel.Results) != 47 {
		t.Errorf("Expected 47 results got %v\n", len(rel.Results))
	}
}
