package entity

import "testing"

const testdata = `
{
                    "status": "OK",
                    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
                    "url": "",
                    "totalTransactions": "3",
                    "language": "english",
                    "entities": [
                        {
                            "type": "Person",
                            "relevance": "0.89066",
                            "knowledgeGraph": {
                                "typeHierarchy": "/people/elliot turner"
                            },
                            "sentiment": {
                                "type": "positive",
                                "score": "0.234428",
                                "mixed": "1"
                            },
                            "count": "7",
                            "text": "Elliot Turner",
                            "quotations": [
                                {
                                    "quotation": "\"Context is super-important,\" he adds ...",
                                    "sentiment": {
                                        "type": "neutral"
                                    }
                                },
                                {
                                    "quotation": "\"'I'm dying' is a lot different than 'I'm dying to buy the new iPhone.'\" \"As we move into new markets, we're going to be making some new hires,\" Turner says ...",
                                    "sentiment": {
                                        "type": "positive",
                                        "score": "0.0743236",
                                        "mixed": "1"
                                    }
                                },
                                {
                                    "quotation": "\"We knocked down some walls and added 2,000 square feet to our office.\" \"We're providing the ability to translate human language in the form of web pages and documents into actionable data,\" Turner says",
                                    "sentiment": {
                                        "type": "negative",
                                        "score": "-0.0207915",
                                        "mixed": "1"
                                    }
                                },
                                {
                                    "quotation": "\"This allows a news organization to detect what a person likes to read about,\" says Turner ...",
                                    "sentiment": {
                                        "type": "positive",
                                        "score": "0.241649"
                                    }
                                }
                            ]
                        },
                        {
                            "type": "PrintMedia",
                            "relevance": "0.252507",
                            "knowledgeGraph": {
                                "typeHierarchy": "/sources/wire services/pr newswire"
                            },
                            "sentiment": {
                                "type": "neutral"
                            },
                            "count": "1",
                            "text": "PR Newswire"
                        },
                        {
                            "type": "Company",
                            "relevance": "0.233257",
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/businesses/retailers/walmart"
                            },
                            "sentiment": {
                                "type": "positive",
                                "score": "0.260944"
                            },
                            "count": "1",
                            "text": "Walmart"
                        },
                        {
                            "type": "Company",
                            "relevance": "0.211686",
                            "sentiment": {
                                "type": "positive",
                                "score": "0.274219"
                            },
                            "count": "1",
                            "text": "AlchemyAPI"
                        },
                        {
                            "type": "Technology",
                            "relevance": "0.163204",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "count": "1",
                            "text": "iPhone."
                        },
                        {
                            "type": "Quantity",
                            "relevance": "0.163204",
                            "knowledgeGraph": {
                                "typeHierarchy": "/points/threes/three years"
                            },
                            "sentiment": {
                                "type": "neutral"
                            },
                            "count": "1",
                            "text": "three years"
                        }
                    ]
                }`

func TestEntity(t *testing.T) {
	e := Entity{}
	err := e.Decode([]byte(testdata))
	if err != nil {
		t.Error(err)
	}
	if len(e.Results) != 6 {
		t.Errorf("Expected 6 results got %v\n", len(e.Results))
	}
}
