// Copyright 2015 Davin Hills. All rights reserved.
// MIT license. License details can be found in the LICENSE file.

package sentiment

import "testing"

const testdata = `
{
	"status": "OK",
	"usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
	"url": "http://www.desmoinesregister.com/story/news/crime-and-courts/2015/07/14/van-meter-taser-fundraiser-modified/30129893/?hootPostID=%5B%22%5B%27e34bfcfff7cf7090f7c60c8ecd6167a8%27%5D%22%5D",
	"totalTransactions": "1",
	"language": "english",
	"docSentiment": {
			"mixed": "1",
			"score": "0.0258114",
			"type": "positive"
	}
}
`

func TestTaxonomy(t *testing.T) {
	s := Sentiments{}
	err := s.Decode([]byte(testdata))
	if err != nil {
		t.Error(err)
	}
}
