package keyword

import "testing"

const tjson = `
{
                    "status": "OK",
                    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
                    "url": "http://www.desmoinesregister.com/story/news/crime-and-courts/2015/07/14/van-meter-taser-fundraiser-modified/30129893/?hootPostID=%5B%22%5B%27e34bfcfff7cf7090f7c60c8ecd6167a8%27%5D%22%5D",
                    "totalTransactions": "3",
                    "language": "english",
                    "keywords": [
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/places/cities/van meter city"
                            },
                            "relevance": "0.9197",
                            "sentiment": {
                                "score": "-0.465221",
                                "type": "negative"
                            },
                            "text": "van meter city"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/goodies/raffle tickets"
                            },
                            "relevance": "0.699297",
                            "sentiment": {
                                "score": "0.389972",
                                "type": "positive"
                            },
                            "text": "raffle tickets"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/people/meter city official"
                            },
                            "relevance": "0.692737",
                            "sentiment": {
                                "score": "-0.695416",
                                "type": "negative"
                            },
                            "text": "Meter city official"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/activities/events/raffles/taser raffle"
                            },
                            "relevance": "0.672875",
                            "sentiment": {
                                "score": "0.643118",
                                "type": "positive"
                            },
                            "text": "Taser raffle"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/experts/city administrators/city administrator jake"
                            },
                            "relevance": "0.661706",
                            "sentiment": {
                                "score": "0.330131",
                                "type": "positive"
                            },
                            "text": "City Administrator Jake"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/characters/bob/councilman bob lacy"
                            },
                            "relevance": "0.643354",
                            "sentiment": {
                                "score": "0.330131",
                                "type": "positive"
                            },
                            "text": "Councilman Bob Lacy"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/activities/fundraising/commendable fundraising efforts"
                            },
                            "relevance": "0.639013",
                            "sentiment": {
                                "score": "0.600424",
                                "type": "positive"
                            },
                            "text": "commendable fundraising efforts"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/agencies/police/police taser"
                            },
                            "relevance": "0.637554",
                            "sentiment": {
                                "score": "-0.517203",
                                "type": "negative"
                            },
                            "text": "police Taser"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/places/buildings/city hall/meter city hall"
                            },
                            "relevance": "0.633844",
                            "sentiment": {
                                "score": "-0.235027",
                                "type": "negative"
                            },
                            "text": "Meter City Hall"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/activities/events/raffles/fundraising raffle"
                            },
                            "relevance": "0.621193",
                            "sentiment": {
                                "score": "-0.517203",
                                "type": "negative"
                            },
                            "text": "fundraising raffle"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/communities/dallas county/dallas county dispatch"
                            },
                            "relevance": "0.6125",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "Dallas County dispatch"
                        },
                        {
                            "relevance": "0.608909",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "Chief Bill Daggett"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/activities/events/original tasing event"
                            },
                            "relevance": "0.604913",
                            "sentiment": {
                                "score": "-0.401895",
                                "type": "negative"
                            },
                            "text": "original Tasing event"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/government agencies/law enforcement/law enforcement personnel"
                            },
                            "relevance": "0.595037",
                            "sentiment": {
                                "score": "0.38165",
                                "type": "positive"
                            },
                            "text": "law enforcement personnel"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/activities/services/resources/materials/news releases/news release states"
                            },
                            "relevance": "0.589187",
                            "sentiment": {
                                "score": "-0.254368",
                                "type": "negative"
                            },
                            "text": "news release states"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/companies/start-ups/des moines-based start-up"
                            },
                            "relevance": "0.584194",
                            "sentiment": {
                                "score": "0.295727",
                                "type": "positive"
                            },
                            "text": "Des Moines-based start-up"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/national meets/non/non lethal force"
                            },
                            "relevance": "0.575393",
                            "sentiment": {
                                "score": "-0.399424",
                                "type": "negative"
                            },
                            "text": "non lethal force"
                        },
                        {
                            "relevance": "0.571372",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "purchase oxygen masks"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/words/wise/wise tactical products"
                            },
                            "relevance": "0.567195",
                            "sentiment": {
                                "score": "0.295727",
                                "type": "positive"
                            },
                            "text": "Wise Tactical Products"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/communities/community/community efforts"
                            },
                            "relevance": "0.477988",
                            "sentiment": {
                                "score": "0.278933",
                                "type": "positive"
                            },
                            "text": "community efforts"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/people/players/owens/j.c. owens"
                            },
                            "relevance": "0.468841",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "J.C. Owens"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/films/public eye"
                            },
                            "relevance": "0.468694",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "public eye"
                        },
                        {
                            "relevance": "0.468401",
                            "sentiment": {
                                "score": "0.278933",
                                "type": "positive"
                            },
                            "text": "undated letter"
                        },
                        {
                            "relevance": "0.46761",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "six-person force"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/animals/humans/human element"
                            },
                            "relevance": "0.466502",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "human element"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/factors/international attention"
                            },
                            "relevance": "0.463422",
                            "sentiment": {
                                "score": "0.320664",
                                "type": "positive"
                            },
                            "text": "international attention"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/issues/concerns/important concerns"
                            },
                            "relevance": "0.462056",
                            "sentiment": {
                                "score": "0.643118",
                                "type": "positive"
                            },
                            "text": "important concerns"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/concepts/factors/skills/understanding/better understanding"
                            },
                            "relevance": "0.461216",
                            "sentiment": {
                                "score": "0.55177",
                                "type": "positive"
                            },
                            "text": "better understanding"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/people/jeremy rosen"
                            },
                            "relevance": "0.460054",
                            "sentiment": {
                                "score": "0.228908",
                                "type": "positive"
                            },
                            "text": "Jeremy Rosen"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/products/stun guns/tasers/dangerous tasers"
                            },
                            "relevance": "0.458168",
                            "sentiment": {
                                "score": "0.55177",
                                "type": "positive"
                            },
                            "text": "dangerous Tasers"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/companies/organizations/facebook page"
                            },
                            "relevance": "0.457782",
                            "sentiment": {
                                "score": "0.642021",
                                "type": "positive"
                            },
                            "text": "Facebook page"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/issues/policies/clear policies"
                            },
                            "relevance": "0.454809",
                            "sentiment": {
                                "score": "0.38165",
                                "type": "positive"
                            },
                            "text": "clear policies"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/people/government officials"
                            },
                            "relevance": "0.452966",
                            "sentiment": {
                                "score": "-0.235027",
                                "type": "negative"
                            },
                            "text": "government officials"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/products/materials/services/resources/equipment/siren equipment"
                            },
                            "relevance": "0.451767",
                            "sentiment": {
                                "score": "0.295727",
                                "type": "positive"
                            },
                            "text": "siren equipment"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/citizens/community citizen"
                            },
                            "relevance": "0.451514",
                            "sentiment": {
                                "score": "-0.467557",
                                "type": "negative"
                            },
                            "text": "community citizen"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/vehicles/cars/squad car"
                            },
                            "relevance": "0.449692",
                            "sentiment": {
                                "score": "-0.388342",
                                "type": "negative"
                            },
                            "text": "squad car"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/educational/educational direction"
                            },
                            "relevance": "0.447257",
                            "sentiment": {
                                "score": "-0.399424",
                                "type": "negative"
                            },
                            "text": "educational direction"
                        },
                        {
                            "relevance": "0.446772",
                            "sentiment": {
                                "score": "0.278933",
                                "type": "positive"
                            },
                            "text": "funding gap"
                        },
                        {
                            "relevance": "0.442833",
                            "sentiment": {
                                "score": "0.295727",
                                "type": "positive"
                            },
                            "text": "patrol vehicle"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/places/states/iowa"
                            },
                            "relevance": "0.371725",
                            "sentiment": {
                                "score": "-0.387138",
                                "type": "negative"
                            },
                            "text": "Iowa"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/groups/aclu"
                            },
                            "relevance": "0.369447",
                            "sentiment": {
                                "score": "-0.379759",
                                "type": "negative"
                            },
                            "text": "ACLU"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/businesses"
                            },
                            "relevance": "0.354999",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "businesses"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/products/materials/services/resources/money"
                            },
                            "relevance": "0.352935",
                            "sentiment": {
                                "score": "-0.235027",
                                "type": "negative"
                            },
                            "text": "money"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/organizations/service providers/partners/officers"
                            },
                            "relevance": "0.341974",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "officers"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/products/medical devices/defibrillators"
                            },
                            "relevance": "0.332494",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "defibrillators"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/products/materials/flier"
                            },
                            "relevance": "0.332434",
                            "sentiment": {
                                "score": "0.642021",
                                "type": "positive"
                            },
                            "text": "flier"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/statements/plan"
                            },
                            "relevance": "0.329702",
                            "sentiment": {
                                "score": "0.330131",
                                "type": "positive"
                            },
                            "text": "plan"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/counties/anderson"
                            },
                            "relevance": "0.329554",
                            "sentiment": {
                                "score": "0.330131",
                                "type": "positive"
                            },
                            "text": "Anderson"
                        },
                        {
                            "relevance": "0.329356",
                            "sentiment": {
                                "score": "-0.235027",
                                "type": "negative"
                            },
                            "text": "intention"
                        },
                        {
                            "knowledgeGraph": {
                                "typeHierarchy": "/issues/benefits/opportunity"
                            },
                            "relevance": "0.327239",
                            "sentiment": {
                                "type": "neutral"
                            },
                            "text": "opportunity"
                        }
                    ]
                }

`

func TestKeyword(t *testing.T) {
	k := Keyword{}
	if err := k.Decode([]byte(tjson)); err != nil {
		t.Error(err)
	}
	if len(k.Results) != 50 {
		t.Errorf("Expected 50 results got %v\n", len(k.Results))
	}
}
